version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wallet_db
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qweasd123
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d wallet" ]
      interval: 5s
      timeout: 5s
      retries: 10

  wallet-app:
    build: .
    container_name: wallet_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8083
    volumes:
      - ./config:/app/config
    ports:
      - "8083:8084"

volumes:
  pg_data: